version: 1
metadata:
  name: CCO CLI OAuth2 Provider
  labels:
    app: cco-cli
    type: oauth2-provider

entries:
  - model: authentik_providers_oauth2.oauth2provider
    id: cco-cli-provider
    identifiers:
      name: CCO CLI Provider
    attrs:
      name: CCO CLI Provider

      # Client Configuration
      client_type: public
      client_id: cco-cli
      client_secret: ""  # Empty for public clients

      # Token Validity
      access_token_validity: hours=1
      refresh_token_validity: days=30

      # Authorization Flow
      # Note: Replace with your actual flow slug/UUID
      authorization_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]

      # OIDC Configuration
      include_claims_in_id_token: true
      issuer_mode: per_provider
      sub_mode: hashed_user_id

      # Redirect URIs (empty for device flow)
      redirect_uris: ""

      # Signing Configuration
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]

      # Advanced Settings
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]

      # Device Flow Settings
      # Authentik automatically supports device flow if client_type is public

  - model: authentik_providers_oauth2.scopemapping
    id: cco-cli-groups-scope
    identifiers:
      scope_name: groups
    attrs:
      name: CCO CLI Groups Scope
      scope_name: groups
      description: Include user groups in token claims
      expression: |
        return {
          "groups": [group.name for group in user.ak_groups.all()],
        }

context:
  cco-cli-provider: !KeyOf cco-cli-provider

# Usage Instructions:
#
# 1. Save this file as cco-oauth2-provider.yaml
#
# 2. Apply via Authentik API:
#    curl -X POST https://auth.visiquate.com/api/v3/managed/blueprints/apply/ \
#      -H "Authorization: Bearer YOUR_API_TOKEN" \
#      -H "Content-Type: application/yaml" \
#      --data-binary @cco-oauth2-provider.yaml
#
# 3. Or via Authentik Web UI:
#    - Navigate to Blueprints
#    - Click "Import"
#    - Upload this file
#    - Click "Apply"
#
# 4. Verify provider creation:
#    curl https://auth.visiquate.com/api/v3/providers/oauth2/?name=CCO%20CLI%20Provider \
#      -H "Authorization: Bearer YOUR_API_TOKEN"
#
# Notes:
# - The authorization_flow must exist before applying this blueprint
# - Default flow slug is "default-authentication-flow"
# - Adjust flow reference if using custom authentication flow
# - The signing key uses Authentik's default self-signed certificate
# - Consider using a custom certificate in production
